apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    spec:
      securityContext:
        fsGroup: 7474
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
      - name: code-il2-pull-creds
      containers:
      - name: neo4j
        image: neo4j
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: neo4j-secrets
        env:
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        ports:
        - containerPort: 7687
        - containerPort: 7474
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
          - name: neo4j-data
            mountPath: "/data"
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc
