apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: eccr-cds
  authentication: istio-auth

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: cds-nginx-default-config
  files:
  - nginx.conf
