apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ECCR-CMS
  authentication: istio-auth

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: cms-nginx-default-config
  files:
  - nginx.conf

